fix: Add workaround for ESP32S2 compilation failure
Previous attempts of compilation failed due to the linker not
finding a specific library. This resulted in the following error:
```
xtensa-esp32s2-elf-gcc-ar: Cannot find plugin 'liblto_plugin.so'
```

Workaround is to disable LTO for the compilation, which can only be
done reliably by a PIO extra_script.